import './globals.css'
import type { Metadata } from 'next'
import Navbar from './component/Navbar/Navbar'
import { Nunito_Sans, Raleway } from 'next/font/google'


const raleway = Raleway({
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap',
})

const nunito_sans = Nunito_Sans({
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={nunito_sans.className}>
        <Navbar />  
        {children}
        </body>
    </html>
  )
}
